#!/usr/bin/env bash
#
# Install a sudoers drop-in that grants the current user passwordless access
# to the specific commands needed by the GLIM test suite.
#
# Setup:   sudo bash tests/setup-sudo.sh
# Teardown: sudo bash tests/setup-sudo.sh --remove
#

set -euo pipefail

SUDOERS_FILE="/etc/sudoers.d/glim-tests"

if [[ $(id -u) -ne 0 ]]; then
  echo "ERROR: Run this script with sudo: sudo bash $0"
  exit 1
fi

if [[ "${1:-}" == "--remove" ]]; then
  if [[ -f "$SUDOERS_FILE" ]]; then
    rm "$SUDOERS_FILE"
    echo "Removed: $SUDOERS_FILE"
  else
    echo "Nothing to remove: $SUDOERS_FILE does not exist."
  fi
  exit 0
fi

CURRENT_USER="${SUDO_USER:-$(logname)}"

# Commands required by the test suite
CMDS=(
  /usr/sbin/losetup
  /usr/sbin/partprobe
  /usr/sbin/sgdisk
  /sbin/sfdisk
  /usr/sbin/mkfs.ext4
  /usr/sbin/mkfs.exfat
  /usr/sbin/mkfs.vfat
  /usr/bin/mount
  /usr/bin/umount
  /usr/sbin/udevadm
  /usr/bin/sync
  /bin/dd
  /usr/bin/chown
  /usr/bin/chmod
  /usr/bin/lsblk
  /usr/bin/blkid
  /usr/sbin/grub-install
  /usr/sbin/grub2-install
)

# Build comma-separated command list, only including paths that exist
ALLOWED=""
for cmd in "${CMDS[@]}"; do
  # Also check without the full path prefix (distro differences)
  actual=$(command -v "$(basename "$cmd")" 2>/dev/null || true)
  if [[ -n "$actual" ]]; then
    if [[ -n "$ALLOWED" ]]; then
      ALLOWED="${ALLOWED}, ${actual}"
    else
      ALLOWED="${actual}"
    fi
  fi
done

if [[ -z "$ALLOWED" ]]; then
  echo "ERROR: No matching commands found. Is the test environment set up?"
  exit 1
fi

cat > "$SUDOERS_FILE" <<EOF
# Passwordless sudo for GLIM test suite — generated by tests/setup-sudo.sh
# Remove with: sudo rm $SUDOERS_FILE
${CURRENT_USER} ALL=(root) NOPASSWD: ${ALLOWED}
EOF

chmod 440 "$SUDOERS_FILE"

# Validate the file is syntactically correct before leaving it in place
if ! visudo -cf "$SUDOERS_FILE"; then
  rm "$SUDOERS_FILE"
  echo "ERROR: Generated sudoers file failed validation. Removed."
  exit 1
fi

echo "Installed: $SUDOERS_FILE"
echo "User '$CURRENT_USER' can now run the following without a password:"
echo ""
echo "$ALLOWED" | tr ',' '\n' | sed 's/^ */  /'
echo ""
echo "Run tests with:  uv run tests/run.py"
